SELECT ENAME, EMP.DEPTNO, DNAME
FROM EMP, DEPT; -- ENTITY(테이블을 객체화한 단어);

SELECT ENAME, E.DEPTNO, DNAME
FROM EMP E, DEPT D;

ROWID, ROWNUM
-> 테이블 생성 후 데이터를 ROW 단위로 입력할 때 자동으로 생성되는 컬럼의 속성값

데이터 무결성 제약조건 확인
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS;


불러와서 생성하는경우도 있음.
CREATE TABLE TEST01(MYNAME, MYSAL)
  AS
  SELECT ENAME, SAL FROM EMP;

구조만 가져오기
CREATE TABLE TEST02
AS
SELECT * FROM EMP
WHERE 1 = 0;
